### ISSUE TITLE
Incorrect functions of the parameter wheel

### ISSUE THREAD

**Issue by gbdomubpkm** [mymike00/Yatzy#8]
The parameter wheel does not perform its functions: it only restarts a part, like the arrow rolled up just to its right.

**Comment by mymike00** [comment]
> it only restarts a part

what do you mean?

the "settings" icon is to switch between yatzy and kniffel mode, that have different score rules. Switching game mode needs of course to reset the current match

**Comment by gbdomubpkm** [comment]
Is that it?  Okay. You are absolutely right indeed. A thousand apologies. I close the bug report that has no reason to be.

**Comment by mymike00** [comment]
well yeah, it's not the best UX... it probably needs to be fixed in the future...
